const path = require('path');

/**
 * Converts extracted data into a lean markdown summary for AGENTS.md.
 * Detailed content lives in .carto/context/*.md domain files.
 */
function formatSections({ routes, models, frontend, structure, warnings, fileMap, functions, dbTables, envVars, importGraph, stackItems, entryPoints, highImpact }) {
  const sections = [];

  // 1. Project Structure
  sections.push('## Project Structure (auto)\n');
  if (structure.length > 0) {
    for (const entry of structure) {
      const icon = entry.type === 'dir' ? '📁' : '📄';
      const suffix = entry.type === 'dir' ? '/' : '';
      sections.push(`- ${icon} ${entry.name}${suffix}`);
    }
  } else {
    if (process.env.CARTO_DEBUG) {
      console.warn('[CARTO] Warning: structure data was empty when formatting AGENTS.md');
    }
    sections.push('_No structure data available._');
  }

  // Stack line — right after structure
  if (stackItems && stackItems.length > 0) {
    sections.push(`\n**Stack:** ${stackItems.join(', ')}`);
  }

  // Entry points
  if (entryPoints && entryPoints.length > 0) {
    sections.push(`**Entry points:** ${entryPoints.join(', ')}`);
  }

  // High impact files
  if (highImpact && highImpact.length > 0) {
    const items = highImpact.map(h => `${h.file} (${h.count} dependents)`);
    sections.push(`**High impact:** ${items.join(', ')}`);
  }

  // 2. Context Files (replaces File Map)
  sections.push('\n## Context Files (auto)\n');
  sections.push('Carto generated domain-specific context files in `.carto/context/`.');
  sections.push('Read the relevant file before working on that area:\n');
  sections.push('| Domain | File | Read when... |');
  sections.push('|--------|------|--------------|');
  sections.push('| Auth | `.carto/context/AUTH.md` | Working on login, sessions, OAuth |');
  sections.push('| Payments | `.carto/context/PAYMENTS.md` | Working on billing, Stripe |');
  sections.push('| tRPC | `.carto/context/TRPC.md` | Working on API procedures |');
  sections.push('| Database | `.carto/context/DATABASE.md` | Working on models, schema |');
  sections.push('| Events | `.carto/context/EVENTS.md` | Working on webhooks, jobs |');
  sections.push('| Core | `.carto/context/CORE.md` | General utilities, shared code |');

  sections.push('\n> Run `carto serve` to enable live graph queries from Kiro, Cursor, and Claude.');

  return sections.join('\n');
}

/**
 * formatDomainFile(domainName, cluster) → markdown string
 * Formats a single domain's data as a standalone markdown file.
 */
function formatDomainFile(domainName, cluster) {
  const sections = [];
  sections.push(`# ${domainName} (auto-generated by Carto)\n`);
  sections.push(`> Read this when working on ${domainName.toLowerCase()} features.\n`);

  if (cluster.routes.length > 0) {
    sections.push('## Routes\n');
    sections.push('| Method | Path | Handler |');
    sections.push('|--------|------|---------|');
    for (const r of cluster.routes) {
      sections.push(`| ${r.method} | ${r.path} | ${r.functionName} |`);
    }
    sections.push('');
  }

  if (cluster.models.length > 0) {
    sections.push('## Models\n');
    for (const m of cluster.models) {
      sections.push(`### ${m.className}`);
      if (m.fields.length > 0) {
        sections.push('| Field | Type |');
        sections.push('|-------|------|');
        for (const f of m.fields) {
          sections.push(`| ${f.name} | ${f.type} |`);
        }
      }
      sections.push('');
    }
  }

  if (Object.keys(cluster.functions).length > 0) {
    sections.push('## Functions\n');
    for (const [file, funcs] of Object.entries(cluster.functions)) {
      if (funcs.length === 0) continue;
      sections.push(`### ${file}`);
      sections.push('| Function | Params | Returns |');
      sections.push('|----------|--------|---------|');
      for (const f of funcs) {
        sections.push(`| ${f.name} | ${f.params} | ${f.returnType} |`);
      }
      sections.push('');
    }
  }

  if (cluster.dbTables.length > 0) {
    sections.push('## Database Tables\n');
    sections.push('| Table | Model | File |');
    sections.push('|-------|-------|------|');
    for (const t of cluster.dbTables) {
      sections.push(`| ${t.tableName} | ${t.modelName} | ${t.file} |`);
    }
    sections.push('');
  }

  if (cluster.envVars.length > 0) {
    sections.push('## Environment Variables\n');
    sections.push('| Variable | Used In |');
    sections.push('|----------|---------|');
    for (const v of cluster.envVars) {
      sections.push(`| ${v.name} | ${v.files.join(', ')} |`);
    }
    sections.push('');
  }

  if (cluster.fileMap.length > 0) {
    sections.push('## Files\n');
    sections.push('| File | Responsibility |');
    sections.push('|------|----------------|');
    for (const entry of cluster.fileMap) {
      sections.push(`| ${entry.file} | ${entry.responsibility} |`);
    }
  }

  return sections.join('\n');
}

module.exports = { formatSections, formatDomainFile };
